from sql import query


def main():

    # -------DROP-------
    query("""DROP TABLE `QUESTION`;""")
    query("""DROP TABLE `BEACON_LOCATION`;""")
    query("""DROP TABLE `USERS`;""")
    query("""DROP TABLE `USER_EVENTS`;""")
    query("""DROP TABLE `BEACON_EVENT`;""")
    query("""DROP TABLE `EVENT`;""")
    query("""DROP TABLE `USER_QUESTIONS`;""")
    query("""DROP TABLE `USER_BEACONS`;""")
    query("""DROP TABLE `USER_EVENT_STATISTIC`;""")

    # -------CREATE-------
    query("""CREATE TABLE `QUESTION` (`ID`	INTEGER, `QUESTION`	TEXT, `ANSWER1`	TEXT, `ANSWER2`	TEXT, `ANSWER3`	TEXT, `ANSWER4`	TEXT, `CORRECT`	TEXT, `ID_EVENT`	INTEGER, PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `BEACON_LOCATION` (`ID`	INTEGER,`ID_BEACON`	TEXT,`LOCATION1`	TEXT,`LOCATION2`	TEXT,`LOCATION3`	TEXT,`LOCATION4`	TEXT,`CORRECT`	TEXT,`HINT`	TEXT,PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `USERS` (`ID`	INTEGER,`MAIL`	TEXT,`PASSWORD`	TEXT,`ACCOUNT_TYPE`	TEXT,PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `USER_EVENTS` (`ID`	INTEGER,`USER_ID`	INTEGER,`EVENT_ID`	INTEGER,PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `BEACON_EVENT` (`ID`	INTEGER,`EVENT_ID`	INTEGER,`BEACON_ID`	TEXT,PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `EVENT` (`EVENT_ID`	INTEGER,`EVENT_NAME`	TEXT,`LOCATION`	TEXT,PRIMARY KEY(`EVENT_ID`));""")
    query("""CREATE TABLE `USER_QUESTIONS` (`ID`	INTEGER,`USER_ID`	INTEGER,`QUESTION_ID`	INTEGER,PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `USER_BEACONS` (`ID`	INTEGER,`USER_ID`	INTEGER,`BEACON_ID`	TEXT,`EVENT_ID`	INTEGER,	`BOOL`	INTEGER,	PRIMARY KEY(`ID`));""")
    query("""CREATE TABLE `USER_EVENT_STATISTIC` (`ID`	INTEGER,`USER_ID`	INTEGER,`PKT`	INTEGER,`COUNT_ANSWERS`	INTEGER,`EVENT_ID`	INTEGER,PRIMARY KEY(`ID`));""")

    # -------NEW RECORDS-------
    query("""INSERT INTO `USERS` (MAIL,PASSWORD,ACCOUNT_TYPE) VALUES ('u@u','uuu','user');""")
    query("""INSERT INTO `USERS` (MAIL,PASSWORD,ACCOUNT_TYPE) VALUES ('a@a','aaa','admin');""")

if __name__ == '__main__':
    main()
